### ISSUE TITLE
simple jpg upload from CLI or Python script won't work... [BUG]

### ISSUE THREAD

**Issue by a3igner** [b3nab/instapy-cli#101]
**output:**
[IG] re-use cookie from XXMYUSERNAMEXX_ig.json
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "upload.py", line 9, in <module>
    cli.upload(image, text)
  File "/home/a3/.local/lib/python3.8/site-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.

**called from commandline:**
instapy -u XXX -p XXX -f the_porpoise_galaxy_from_hubble_sd_2020-05-10.jpg -t 'NASA PIC OF DAY #spaceporn #beautiful'

**or tried using python code**
```
from instapy_cli import client

username = 'XXX'
password = 'XXX'
image = 'the_porpoise_galaxy_from_hubble_sd_2020-05-10.jpg'
text = 'NASA pic of the day' + '\r\n' + '#spaceporn #beautiful'
print(username,password,image,text)
with client(username, password) as cli:
        cli.upload(image, text)
```

 - OS: Ubuntu 18.04
 - Python: 3.8.2
 - instapy-cli Version: 0.0.12

**Comment by a3igner** [comment]
Nope thats not the issue. The cookie is there and works. Some software issue it is.
