### ISSUE TITLE
[BUG] cannot upload an image 

### ISSUE THREAD

**Issue by debjit31** [b3nab/instapy-cli#102]
[IG] not found cookie/cookie_file >> login as default
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "code.py", line 10, in <module>
    cli.upload(image, text)
  File "C:\Users\Debjit\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy_cli\cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.

facing this error to just upload a simple image

**Comment by debjit31** [comment]
none of the issues are either solved.......
please inform the maintainers

**Comment by SteBurz** [comment]
I've made a video about his here [why the instagram automation will fail.](https://youtu.be/V09fW6ZRraE)
I think this repo needs to be updated to the new API or the official API needs to be opened up (if this hasn't already happend).
