### ISSUE TITLE
[BUG] can't upload image

### ISSUE THREAD

**Issue by fendiirfan** [b3nab/instapy-cli#103]
[IG] not found cookie/cookie_file >> login as default
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "instagram.py", line 8, in <module>
    cli.upload(image, text)
  File "C:\Users\Fendi Irfan\AppData\Local\Programs\Python\Python38\lib\site-packages\instapy_cli\cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.

**Comment by SteBurz** [comment]
I've made a video about his here [why the instagram automation will fail.](https://youtu.be/V09fW6ZRraE)
I think this repo needs to be updated to the new API or the official API needs to be opened up (if this hasn't already happend).
