### ISSUE TITLE
Can't upload image[. BUG]

### ISSUE THREAD

**Issue by jborges42** [b3nab/instapy-cli#104]
when I try to run the script...

#response  
```
[IG] not found cookie/cookie_file >> login as default
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "ig.py", line 9, in <module>
    cli.upload(image, text)
  File "/home/borges/Projects/Python/InstaManager/instamanagerenv/lib/python3.6/site-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.

```

**Env:**
 - OS: [e.g. Linux Ubuntu 18.04]
 - Python: [e.g. 3.6.9]

**Comment by lrusik** [comment]
Same

**Comment by mrx23dot** [comment]
same +1

**Comment by RussQuan** [comment]
same here + 1

**Comment by parsamrz** [comment]
same

**Comment by thepasterover** [comment]
Dead Project. Probably due to changes made by Instagram.

**Comment by mrx23dot** [comment]
any alternative? 3party services still work (like scheduled posters)

**Comment by tommy3531** [comment]
Same has any found a solution by chance?

**Comment by SteBurz** [comment]
I've made a video about his here [why the instagram automation will fail.](https://youtu.be/V09fW6ZRraE)
I think this repo needs to be updated to the new API or the official API needs to be opened up (if this hasn't already happend).

**Comment by mehrab-wj** [comment]
Same +1 😢
