### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pixincreate** [b3nab/instapy-cli#106]
**Describe the bug**
I'm unable to login or post anything. Instagram API down? or updating?

**To Reproduce**
Shows nothing but error.

```python
from instapy_cli import client
with client('pixincreate', pswd) as cli:
    cli.upload(IMAGEPATH, TEXT)
```

**Expected behavior**
Paste an Image with the text : "Bot testing..." on my instagram page.

**Logs**
If there are any errors or exceptions, add the logs to help explain your problem.
```
[IG] not found cookie/cookie_file >> login as default
Error is >>
    Not Found

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "F:/Coding/Python/YouTube Automate SocialMedia/YouTube_Share.py", line 79, in <module>
    cli.upload(IMAGEPATH, TEXT)
  File "D:\Python\Python Interpreter\lib\site-packages\instapy_cli\cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.

Process finished with exit code 1
```

**Env (please complete the following information):**
 - OS: Windows 10 64 Bit
 - Python: 3.8.1
 - instapy-cli Version: latest, freshly installed.

**Comment by SteBurz** [comment]
Hi @pixincreate, 
I've made a video about his here [why the instagram automation](https://youtu.be/V09fW6ZRraE) will fail.
I think this repo needs to be updated to the new API or the official API needs to be opened up (if this hasn't already happend).
Cheers.

**Comment by yustiks** [comment]
> Hi @pixincreate,
> I've made a video about his here [why the instagram automation](https://youtu.be/V09fW6ZRraE) will fail.
> I think this repo needs to be updated to the new API or the official API needs to be opened up (if this hasn't already happend).
> Cheers.

10 minutes video? Isn't it too long? One sentence will be sufficient to understand that their API changed.

**Comment by yustiks** [comment]
I experience the same problem.
`    raise IOError("Unable to upload.")
OSError: Unable to upload.`

**Comment by Rodrigo507** [comment]
Apparently the api has changed 😥
