### ISSUE TITLE
I can't upload photos

### ISSUE THREAD

**Issue by ChopsKingsland** [b3nab/instapy-cli#108]
I am trying to post a photo using this library, but it doesn't work...

```
from instapy_cli import client

username = '*************'
password = '****************'
image = 'img/blank.png'
text = 'This will be the caption of your photo.' + '\r\n' + 'You can also use hashtags! #hash #tag #now'

with client(username, password) as cli:
    cli.upload(image, text)
```

and the error I get is:
```
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Not Found

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "d:\Documents\Python\spacexLaunchesIG\instagram.py", line 9, in <module>
    cli.upload(image, text)
  File "C:\Users\charl\AppData\Roaming\Python\Python39\site-packages\instapy_cli\cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.
```

any ideas how to fix this?

**Comment by Caspertje83** [comment]
I have the same issue...

**Comment by GonzoTBA** [comment]
Me neither. I assume the Instagram API changed and this code didn't.

**Comment by jamesspittal** [comment]
> Me neither. I assume the Instagram API changed and this code didn't.

Can anyone confirm whether this is the case or not?

**Comment by GonzoTBA** [comment]
No idea. I just wanted to let you know guys, I finally got it working with the [instabot](https://pypi.org/project/instabot/) module. Pretty straightforward.

**Comment by danmaster** [comment]
Time has passed and the problem persists. Does anyone know if they have a solution or should they go to another module?
The fault is

```
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
     Not found

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli
```

**Comment by RenanNSsh** [comment]
Same here

**Comment by Pasanlaksitha** [comment]
same here and sometimes its says error in aspect ratio

**Comment by Lvc4** [comment]
i have the same problem

**Comment by SlumberDemon** [comment]
Same problem here
