### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nux-xader** [b3nab/instapy-cli#111]
**Describe the bug**
Cant upload video

```python
from instapy_cli import client

username, password = str(open("account.txt", "r").read()).split(" | ")
video = 'Videos/test1.mp4'
text = 'Testing create insta uploader tool.\n\nsample tags! #hash #tag #now'

with client(username, password) as cli:
    cli.upload(video, text)
```

```
I was installed Pillow version 9.0.1 but error message is like this :

[IG] not found cookie/cookie_file >> login as default
Error is >>
    Imageio Pillow requires Pillow, not PIL!

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    cli.upload(video, text)
  File "D:\Project\Python\instagram_bot\env\lib\site-packages\instapy_cli\cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.
```

**Env (please complete the following information):**
 - OS: Windows 10
 - Python: 3.8.5
 - instapy-cli Version: 0.0.12

**Comment by amircliper** [comment]
i have this problem too

**Comment by MikeBozzz** [comment]
Any update on this issue?
