### ISSUE TITLE
Support for PNG

### ISSUE THREAD

**Issue by othaner** [b3nab/instapy-cli#13]
I'm not sure if Instapy-cli has suppor for PNG. It works flawlessly in JPG, but when I've tried to use PNG it gives me this:

```
instapy-cli v.0.0.4
Python version: 3.5.2
use >> instapy -u <USERNAME> -p <PASSWORD> -f <IMAGE.JPG> -t <CAPTION>
Traceback (most recent call last):
  File "/home/othaner/projects/.virtualenvs/randomoji/bin/instapy", line 11, in <module>
    sys.exit(main())
  File "/home/othaner/projects/.virtualenvs/randomoji/lib/python3.5/site-packages/instapy_cli/__main__.py", line 45, in main
    cli.upload(options.file, text)
  File "/home/othaner/projects/.virtualenvs/randomoji/lib/python3.5/site-packages/instapy_cli/cli.py", line 29, in upload
    self._session.configure_photo(media_id, caption)
  File "/home/othaner/projects/.virtualenvs/randomoji/lib/python3.5/site-packages/instapy_cli/api/session.py", line 111, in configure_photo
    raise IOError(resp_json.get('message'))
OSError: Uploaded image isn't in the right format
```

Is that what is happening?

**Comment by b3nab** [comment]
Hi @othaner  that's true.
This is because Instagram APIs support only JPG images. 

I'm not sure to be able to add this feature in less than a couple of weeks.

If anyone is interested the solution is really simple: add PIL or another library to convert PNG to JPG only if the selected photo has .png extension.. then do a PR. 😃

**Comment by othaner** [comment]
Actually, in the script where I'm using instapy-cli, it manipulate a few PNGs and after all exports a JPG for upload.

(I have never made a PR, so let me check how it works)

**Comment by Akshat-mehrotra** [comment]
Simple fix:
`def fix_image(path):
	im = Image.open(path)
	rgb_im = im.convert('RGB')
	path = path[:-4]
	path += '.jpg'
	print('\n now new path {}'.format(path))
	rgb_im.save(path)
	return path
`
