### ISSUE TITLE
OSError: Sorry, there was a problem with your request

### ISSUE THREAD

**Issue by othaner** [b3nab/instapy-cli#15]
After a few weeks of good working I'm getting this error.

```
Traceback (most recent call last):
  File "/.virtualenvs/randomoji/bin/instapy", line 11, in <module>
    sys.exit(main())
  File "/.virtualenvs/randomoji/lib/python3.5/site-packages/instapy_cli/__main__.py", line 43, in main
    with client(options.username, password) as cli:
  File "/.virtualenvs/randomoji/lib/python3.5/site-packages/instapy_cli/cli.py", line 15, in __init__
    self._session.login(username, password)
  File "/.virtualenvs/randomoji/lib/python3.5/site-packages/instapy_cli/api/session.py", line 66, in login
    raise IOError(resp_json.get('message'))
OSError: Sorry, there was a problem with your request.
```
I've login in the account and everything seems normal (there's no checkpoint or something). Any ideas?

**Comment by b3nab** [comment]
Maybe Instagram is migrating its own APIs. I think that we need to check this.
If this is true, instapy-cli won't work until we find another way to post photos to Instagram.

**Comment by b3nab** [comment]
UPDATE: This client still work so it's not instapy-cli concern. 
But...
@othaner I got (probably) your real problem.. you need to login into Instagram from the IP where you use instapy-cli and then go for the checkpoint_required procedure.

Hope you solve. If needed you can re-open this issue.
🥂

**Comment by digital-mine** [comment]
@b3nab Could you please tell me how to "go for the checkpoint_required procedure"?

Thank you
