### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by kippi6171** [b3nab/instapy-cli#34]
Hii

I don't have 2FA enabled, no . alerts when I login to the website however when I try to push a image I get this:

instapy 0.0.6  |  python 2.7.13
Traceback (most recent call last):
  File "/usr/local/bin/instapy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/instapy_cli/__main__.py", line 48, in main
    with client(options.username, password) as cli:
  File "/usr/local/lib/python2.7/dist-packages/instapy_cli/cli.py", line 9, in __init__
    self._session.login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/instapy_cli/api/session.py", line 66, in login
    raise IOError(resp_json.get('message'))
IOError: Sorry, there was a problem with your request.

Am I missing something?

**Comment by Glarity** [comment]
How old is your Instagram account? It took about a week for my new account to start working properly.

**Comment by b3nab** [comment]
@kippi6171 please, re-open this issue with a comment if you run on the same problem.

I'm sure it's the problem @Glarity stated.
🥂
