### ISSUE TITLE
[BUG] Cannot Upload Stories

### ISSUE THREAD

**Issue by LPIX-11** [b3nab/instapy-cli#57]
I'm actually having a problem when uploading stories

I followed the documentation and wrote
```python
instapy -u USR -p PWD -f pyArt.jpeg -s 'Python is an Art.'
```

But it Shows.
```
Traceback (most recent call last):
  File "/usr/local/bin/instapy", line 10, in <module>
    sys.exit(main())
  File "/home/johnson/.local/lib/python3.7/site-packages/instapy_cli/__main__.py", line 47, in main
    cli.upload(options.file, text, story)
  File "/home/johnson/.local/lib/python3.7/site-packages/instapy_cli/cli.py", line 164, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.
```

Env
 - OS: [Linux]
 - Python: [3.7]
 - instapy-cli Version: [instapy-cli 0.0.12]

**Comment by AlejandroAldama** [comment]
Hi, i have the same problem when i try to upload an image to the instagram stories. 
I'm trying to find the issue.

**Comment by ElegantFx** [comment]
Same issue.

**Comment by Lucasmiguelmac** [comment]
Anyone figured this out?

**Comment by LPIX-11** [comment]
Unfortunately not yet

**Comment by iceener** [comment]
same story here.
