### ISSUE TITLE
Unable to upload videos to instagram stories

### ISSUE THREAD

**Issue by sleekmike** [b3nab/instapy-cli#66]
Hello,
I have been trying to upload videos to stories but I have been having this error:

Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Forbidden

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "s.py", line 18, in <module>
    res = cli.upload(image_files[i], story=True)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.

I'm using python 3.7,  instapy-cli  version == 0.0.12, os ubuntu 18

**Comment by alessandrogeof** [comment]
Hi, I have the same problem, did you fix this?

**Comment by FruechteBini** [comment]
same problem here. any fix?

**Comment by anmol-4166** [comment]
same issue , did you fix it?

**Comment by DonyThePony** [comment]
Worked fine for a week.
Now i can not upload anymore.
Same error
