### ISSUE TITLE
[BUG] Upload not working

### ISSUE THREAD

**Issue by vascostmr** [b3nab/instapy-cli#79]
Hi everyone, the upload method in cli.py is not working.

`$instapy -u ***** -p "*****" -f ig.png -t 'post_text'`
```
instapy-cli 0.0.12  |  python 3.6.8
[IG] not found cookie/cookie_file >> login as default
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/vascostmr/ffmpeg_scripts/blog/my_py3/bin/instapy", line 8, in <module>
    sys.exit(main())
  File "/home/vascostmr/ffmpeg_scripts/blog/my_py3/lib/python3.6/site-packages/instapy_cli/__main__.py", line 44, in main
    cli.upload(options.file, text, story)
  File "/home/vascostmr/ffmpeg_scripts/blog/my_py3/lib/python3.6/site-packages/instapy_cli/cli.py", line 166, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.
```

The error is thrown in [upload.py](github.com/ping/instagram_private_api) from the instagram_private_api module, with a "Bad Request" message.

**Comment by bilyboy785** [comment]
Same error with instapy-cli 0.0.12  |  python 3.7.3

**Comment by JannisHajda** [comment]
I got the same error. Hopefully it will be fixed as soon as possible.

**Comment by torres-xyz** [comment]
Same here in instapy-cli 0.0.12 and Python 3.7

**Comment by siskot** [comment]
I have got almost the same error:
 instapy -u s....t -p ****** -f /home/siskot/pic/image-sample-upload.jpg -t 'test picture #first #auto #upload'

instapy-cli 0.0.12  |  python 3.6.8
[IG] not found cookie/cookie_file >> login as default
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "/usr/local/bin/instapy", line 11, in <module>
    load_entry_point('instapy-cli', 'console_scripts', 'instapy')()
  File "/home/siskot/bin/instapy-cli-master/instapy_cli/__main__.py", line 44, in main
    cli.upload(options.file, text, story)
  File "/home/siskot/bin/instapy-cli-master/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.

**Comment by RayChao2016** [comment]
Same here in instapy-cli 0.0.12 and Python 3.7.3
Thanks!

**Comment by QihangFan** [comment]
Same error with instapy-cli 0.0.12 and Python 3.8.0

**Comment by RashminDungrani** [comment]
Same error

No handlers could be found for logger "instagram_private_api.errors"
Error is >>
    Bad Request

Traceback (most recent call last):
    upload()

cli.upload(image, final_caption)
raise IOError("Unable to upload.")
IOError: Unable to upload.

**Comment by anmolagarwal552** [comment]
something wrong with this , same error

**Comment by roycebank** [comment]
if you upload just photos --> https://paste.ubuntu.com/p/mxyYmBpryK/

**Comment by roycebank** [comment]
if you upload just photos ↓
https://paste.ubuntu.com/p/mxyYmBpryK/

**Comment by RayChao2016** [comment]
thanks @roycebank , this works for me.
looks the temporary solution is to use Selenium...

**Comment by Lucasmiguelmac** [comment]
Anyone worked this out? Using selenium in the meantime

**Comment by didduinc** [comment]
> Anyone worked this out? Using selenium in the meantime

Ya, just change the chrome driver path after installing latest version according to 32 or 64 bit.

**Comment by samelakshay** [comment]
In my code, I login successfully but this code `cli.upload(image, text)` doesn't work... Same issue... Who has a solution for this?

**Comment by FourKube** [comment]
@didduinc @Lucasmiguelmac @RayChao2016 @roycebank thanks for the selenium suggestion for the mean time. I have successfully been able to log-in with it, however am having trouble uploading photos. I have tried the code at https://paste.ubuntu.com/p/mxyYmBpryK/, but it has not worked for me. I'm on a mac. How are you able to upload? Thanks

**Comment by RashminDungrani** [comment]
> @didduinc @Lucasmiguelmac @RayChao2016 @roycebank thanks for the selenium suggestion for the mean time. I have successfully been able to log-in with it, however am having trouble uploading photos. I have tried the code at https://paste.ubuntu.com/p/mxyYmBpryK/, but it has not worked for me. I'm on a mac. How are you able to upload? Thanks

`import autoit`
there is module called autoit that's only works on windows os.

what is the solution for instapy_cli ? if anyone able to upload post please replay !!!

**Comment by gyromatical** [comment]
Having this same issue as well. There doesn't appear to be a solution yet.

`instapy -u username -p password -f 1.jpg
instapy-cli 0.0.12  |  python 2.7.17
[IG] not found cookie/cookie_file >> login as default
No handlers could be found for logger "instagram_private_api.errors"
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "/home/username/.local/bin/instapy", line 11, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python2.7/site-packages/instapy_cli/__main__.py", line 44, in main
    cli.upload(options.file, text, story)
  File "/home/username/.local/lib/python2.7/site-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
IOError: Unable to upload.

`

**Comment by viatekh** [comment]
am also having this issue -
```
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "igpython.py", line 30, in <module>
    cli.upload(path+file, text)
  File "/usr/local/lib/python3.7/site-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.
```

**Comment by viatekh** [comment]
example is also broken!

**Comment by roycebank** [comment]
guys i've tried a different method its working for upload videos but i couldnt upgrade method codes bcause i dont have time.
you must connect your ig account with any facebook account then fill mail,passwd with fb account info.
https://paste.ubuntu.com/p/gfnjZ397k7/

**Comment by popama** [comment]
Same issue (Python 2.7.12):

`instagram_private_api.errors: Error parsing error response: No JSON object could be decoded
Error is >>
    Bad Request`

`Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli`

`...`

`ig_res = cli.upload(image, caption)`
`File "/usr/local/lib/python2.7/dist-packages/instapy_cli/cli.py", line 154, in upload`
`    raise IOError("Unable to upload.")`
`IOError: Unable to upload.`

**Comment by pauapaua** [comment]
> 
> 
> guys i've tried a different method its working for upload videos but i couldnt upgrade method codes bcause i dont have time.
> you must connect your ig account with any facebook account then fill mail,passwd with fb account info.
> https://paste.ubuntu.com/p/gfnjZ397k7/
@vitorgalvao roycebank
i think something is wrong with my path.
do have any idea?

`  
```
upload("xxx", "xxx", "./chromedriver.exe", "C:\instagram\tom_.2020-01-02_17-31-38.mp4")


File "main.py", line 46, in upload
    autoit.control_send("Aç", "Edit1", os.path.abspath(contentpth))
  File "E:\coden\instagram\uploaderPy\lib\site-packages\autoit\autoit.py", line 84, in wrapper
    raise AutoItError(err_msg)
autoit.autoit.AutoItError: Window/Control could not be found`
```

**Comment by roycebank** [comment]
@pauapaua  if not window name is Aç you must change all autoit Aç values to window name(according to os language)

if your os language is English:

autoit.win_active("Open")
time.sleep(2)
autoit.control_send("Open", "Edit1", os.path.abspath(contentpth))
time.sleep(1.5)
autoit.control_send("Open", "Edit1", "{ENTER}")

**Comment by innowebka** [comment]
anyone fixed this error ? for python (no selenium)

**instapy-cli 0.0.12  |  python 3.6.8
[IG] not found cookie/cookie_file >> login as default**

**Comment by vascYT** [comment]
I also need help...

**Comment by NaNonnI** [comment]
root@vmi233757:/home/dibot# python upload.py
[IG] not found cookie/cookie_file >> login as default
No handlers could be found for logger "instagram_private_api.errors"
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "upload.py", line 7, in <module>
    cli.upload(image, text)
  File "/usr/local/lib/python2.7/dist-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
IOError: Unable to upload.

**Comment by vascYT** [comment]
Guys. Instagram cut the API Support. You can forget this Python Libary.

**Comment by naveenbharadwaj19** [comment]
So no solution for this ? any other api ?

**Comment by vascYT** [comment]
I didn't find any solutions. Sorry. But if I do I will let you guys know.

**Comment by divyanshu-parihar** [comment]
> 
> 
> Same error with instapy-cli 0.0.12 | python 3.7.3

same with me

**Comment by MirabbosMirzakhmedov** [comment]
It's 2021, any solutions so far?

**Comment by roycebank** [comment]
> It's 2021, any solutions so far?

...

**Comment by JannisHajda** [comment]
Active development stopped a while a go. Maybe gonna do some updates during the Christmas season, but can't promise.

**Comment by nextalgon** [comment]
what kind of libraries recomend you for upload post, posts, stories and videos?
