### ISSUE TITLE
[BUG] OSError: Unable to upload.

### ISSUE THREAD

**Issue by hamdyaea** [b3nab/instapy-cli#84]
[IG] not found cookie/cookie_file >> login as default
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "/usr/bin/instapy", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/instapy_cli/__main__.py", line 44, in main
    cli.upload(options.file, text, story)
  File "/usr/lib/python3.8/site-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.

**Comment by Michael1095** [comment]
Same problem.

```
[IG] not found cookie/cookie_file >> login as default
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "main.py", line 35, in <module>
    featureMenu()
  File "main.py", line 13, in featureMenu
    menu("1")
  File "main.py", line 32, in menu
    post(img_path, desc, hashtags)
  File "/home/titan/Documents/Instagram/autobot/modules/post.py", line 8, in post
    cli.upload(img_path, desc)
  File "/home/titan/.local/lib/python3.6/site-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.
```
Python version 3.6.9

Anyone found a fix?

**Comment by mcpeixoto** [comment]
Same..

**Comment by WoJoosen** [comment]
Same. Python version 3.8

**Comment by trocotronic** [comment]
Same here. Python 3.7

**Comment by pauapaua** [comment]
any news?

**Comment by mcpeixoto** [comment]
I think we're fucked since Instagram is killing the API

Cumprimentos,
Miguel Peixoto






pauapaua <notifications@github.com> escreveu no dia sexta, 3/01/2020 à(s)
16:49:

**Comment by petelah** [comment]
I think it is a no go since Instagram is now punishing people for automated tasks they pick up.

**Comment by CROSP** [comment]
At the same time, https://github.com/dilame/instagram-private-api works like a charm

**Comment by viatekh** [comment]
even the example doesn't work, i guess IG has nuked whatever support there was for this...

**Comment by roycebank** [comment]
#75

**Comment by exblopz** [comment]
I have same problem. Looks like IG delete their API, so anyone who want to post must open IG Apps.

**Comment by ChadLei** [comment]
same problem! this was working for this guy like half a year ago https://www.youtube.com/watch?v=vnfhv1E1dU4

**Comment by SartoRiccardo** [comment]
Same problem as of this day.

**Comment by vadgaard** [comment]
Same here.

**Comment by amitmittal117** [comment]
same here

**Comment by abhayvishnoi** [comment]
still struggling to post a single photo on  instagram why does it sucks so much telegram has the best social media api i have ever used and this zuckerberg make it hard for developers

**Comment by netlob** [comment]
same here :(

**Comment by rhotav** [comment]
Same problem. Python 3.8

**Comment by atharvjairath** [comment]
same here..anyone found a solution please notify
]

**Comment by xandrade** [comment]
Same problem here...

**Comment by ParthMaisheri** [comment]
Facing the same issue

**Comment by bahaasamoudi** [comment]
same :)

**Comment by Hemzyy** [comment]
same here

**Comment by atharvakadlag** [comment]
same error, anybody with solutions?

**Comment by Revisto** [comment]
same , damn

**Comment by ade5791** [comment]
so no fix for this?

**Comment by sjaydeep** [comment]
same error.===> raise IOError("Unable to upload.")

**Comment by 1smaa** [comment]
same error with stories...any solutions?

**Comment by Tatuck** [comment]
Nope, I didn't find the solution

**Comment by exblopz** [comment]
Facebook already close API for Facebook and Instagram. Also change their Policies. 
So if you wanna use API for Facebook and Instagram, you should contact them directly.

**Comment by TheOnlyMula** [comment]
Still no solution, at least I haven't found one yet. Getting error:
```
Error is >>
    Not Found
```
Followed by:
```
raise IOError("Unable to upload.")
OSError: Unable to upload.
```
