### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vladartym** [b3nab/instapy-cli#92]
**Describe the bug**

`Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "instagram.py", line 9, in <module>
    cli.upload(image, text)
  File "/Users/vladartym/.pyenv/versions/3.7.4/lib/python3.7/site-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.
`

**To Reproduce**
Code to reproduce the behavior:

`from instapy_cli import client

username = 'hello'
password = '****'
image = 'ready/vladartym.jpg'
text = 'This will be the caption of your photo.' + '\r\n' + 'You can also use hashtags! #hash #tag #now'

with client(username, password) as cli:
    cli.upload(image, text)`

```python
#code here
```

**Expected behavior**

code not working.

**Logs**
If there are any errors or exceptions, add the logs to help explain your problem.
```

```

**Env (please complete the following information):**
 - OS: [e.g. macOS]
 - Python: [e.g. 3.6]
 - instapy-cli Version: [e.g. 0.0.9.0]

**Additional context**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by imshubbh** [comment]
### **Getting - OSError: Unable to upload.**

this is My code - 


from instapy_cli import client

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

username = '*******'
password = '*******'
image = 'posts/demo2.jpg'

with client(username, password) as cli:
    cli.upload(image)

**Comment by vladartym** [comment]
@imshub is that code working for you?

**Comment by imshubbh** [comment]
> @imshub is that code working for you?

@vladartym For login Yes. For media uploads No.

**Comment by vladartym** [comment]
@imshub have you found any alternatives?

**Comment by imshubbh** [comment]
> @imshub have you found any alternatives?

@vladartym not now.

**Comment by naveenbharadwaj19** [comment]
@imshub  @vladartym  even though i'm facing same error and i got a new error
`OSError: Unable to upload.
instapy-cli 0.0.12  |  python 3.7.4
[IG] not found cookie/cookie_file >> login as default
Error is >>
    Bad Request

Something went bad.
`
`ModuleNotFoundError: No module named 'instapy_cli'`
Any solutions to fix this ?

**Comment by vladartym** [comment]
I think this doesn't work anymore.
