### ISSUE TITLE
Error is >> Bad Request

### ISSUE THREAD

**Issue by SahilMahadwar** [b3nab/instapy-cli#97]
$ python main.py 
[IG] not found cookie/cookie_file >> login as default
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    cli.upload(image, text)
  File "C:\Users\sahil\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy_cli\cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.

**Comment by tomdaly** [comment]
Same as #84

**Comment by benC1232** [comment]
same

**Comment by Masood-Salik** [comment]
Same

**Comment by maazmachkal** [comment]
same

**Comment by dj-bauer** [comment]
I have exactly the same issue. Also I dont get any cookie file generated.
I run:
with instapy_cli.client(insta_name, insta_password) as insta:
    insta.upload(filename, caption)

Edit:
The issue can't be the missing cookie, because I manually generated one like here https://github.com/instagrambot/instapy-cli/blob/master/examples/login-cookie-write-file.py

**Comment by mrkaspa** [comment]
Having the same issue

**Comment by sammarxz** [comment]
Same
